	spring.application.name=transcaribe_db
	
	# Antes: spring.data.mongodb.uri=mongodb://localhost:27017/transcaribe_db
	# Después (Copia y pega esto):
	spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}	
		

	spring.mail.host=smtp.gmail.com
	spring.mail.port=587
	spring.mail.username=transcaribeapp@gmail.com
	spring.mail.password=qfgqxxequczcejmu
	spring.mail.properties.mail.smtp.auth=true
	spring.mail.properties.mail.smtp.starttls.enable=true
	spring.thymeleaf.cache=false
	server.port=8080
	server.servlet.session.timeout=30m
	# --- Configuración de Seguridad JWT ---
	# Esta clave es la que usará JwtService para firmar los tokens. 
	# Asegúrate de que sea larga y secreta.
	app.jwt.secret=${APP_JWT_SECRET}
	# Expiración de 24 horas (en milisegundos)
	app.jwt.expiration-ms=86400000

	# --- Configuración de Google OAuth2 ---
	# Estos datos los obtienes de Google Cloud Console
	spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
	spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
	spring.security.oauth2.client.registration.google.scope=email,profile