

	spring.application.name=transcaribe_db
	
	spring.data.mongodb.uri=mongodb+srv://Admin:RtKGhwlYZ8XNUuSL@cluster0.dhwrxtd.mongodb.net/transcaribe_db
	

	spring.mail.host=smtp.gmail.com
	spring.mail.port=587
	spring.mail.username=transcaribeapp@gmail.com
	spring.mail.password=qfgqxxequczcejmu
	spring.mail.properties.mail.smtp.auth=true
	spring.mail.properties.mail.smtp.starttls.enable=true
	spring.thymeleaf.cache=false
	server.port=8081
	server.servlet.session.timeout=30m
	# --- Configuración de Seguridad JWT ---
	# Esta clave es la que usará JwtService para firmar los tokens. 
	# Asegúrate de que sea larga y secreta.
	app.jwt.secret=ddn72mcGX9V47icYqHQjaYIWh+MoS3R31lyXGAjqffE=
	# Expiración de 24 horas (en milisegundos)
	app.jwt.expiration-ms=86400000

	# --- Configuración de Google OAuth2 ---
	# Estos datos los obtienes de Google Cloud Console
	spring.security.oauth2.client.registration.google.client-id=126707567986-1ejdn0k07gto37kqhg35qdanfonpn92o.apps.googleusercontent.com
	spring.security.oauth2.client.registration.google.client-secret=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
	spring.security.oauth2.client.registration.google.scope=email,profile
	spring.mail.properties.mail.smtp.starttls.required=true
	spring.mail.properties.mail.debug=true