spring.application.name=transcaribe_db

# --- Base de Datos (MongoDB Atlas) ---
# Se recomienda dejar que Spring la detecte o usar el nombre exacto de tu variable en Railway
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# --- Configuración de Correo (Ajustado para Railway) ---
spring.mail.host=smtp.gmail.com
# Cambiamos a 587 porque el puerto 465 suele estar bloqueado por seguridad en muchos hostings
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
# Para el puerto 587, STARTTLS debe estar en true y SSL en false
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false

# --- Configuración del Servidor ---
server.forward-headers-strategy=native
spring.thymeleaf.cache=false
server.port=${PORT:8080}
server.servlet.session.timeout=30m

# --- Seguridad JWT ---
app.jwt.secret=${APP_JWT_SECRET}
# Expiración de 24 horas
app.jwt.expiration-ms=86400000

# --- Google OAuth2 ---
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile